# Generated by Django 3.2.25 on 2026-08-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=100)),
                ('fixture', models.CharField(max_length=100)),
                ('work_offset', models.CharField(max_length=20)),
                ('drawing_number', models.CharField(max_length=50)),
                ('drawing_revision', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
