# Generated by Django 3.2.25 on 2026-08-31 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.TextField()),
                ('datum', models.CharField(max_length=100)),
                ('clamping', models.TextField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workpiece', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_number', models.CharField(max_length=20)),
                ('tool_type', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=50)),
                ('revision', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed')], default='READY', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed_parts', models.PositiveIntegerField(default=0)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='MachineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_checks', to='jobs.job')),
            ],
        ),
    ]
