# Generated by Django 3.2.25 on 2026-08-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_machinecheck_operation_tool_workpiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
