# Generated by Django 3.2.25 on 2026-08-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_tool_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpiece',
            name='clamping_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workpiece',
            name='datum_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workpiece',
            name='orientation_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
