# Generated by Django 3.2.25 on 2026-08-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20260831_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
